-- CREATE EXTENSION postgis;
--
-- CREATE schema public;

CREATE ROLE rstyler_data_steward LOGIN PASSWORD '%5KFx$WRp4W#';

CREATE TABLE river_styles (
    river_style_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_name       VARCHAR(255) UNIQUE NOT NULL,
    description     TEXT
);

CREATE TABLE procedural_trees (
    tree_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_name       VARCHAR(255) UNIQUE NOT NULL,
    description     TEXT,
    parent_rule_id  INT NOT NULL,

    CONSTRAINT fk_procedural_trees_parent_rule_id FOREIGN KEY (parent_rule_id) REFERENCES rules(rule_id)
);
CREATE INDEX fx_procedural_trees_parent_rule_id ON procedural_trees(parent_rule_id);

CREATE TABLE rules (
    rule_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id         INT NOT NULL,
    name            VARCHAR(255),
    description     TEXT,

    CONSTRAINT fk_rules_tree_id FOREIGN KEY (tree_id) REFERENCES procedural_trees(tree_id)
);
CREATE INDEX fx_rules_tree_id ON rules(tree_id);

CREATE TABLE rule_bins (
    bin_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id         INT NOT NULL,
    name            VARCHAR(255),
    indicator_id    INT NOT NULL,
    criteria        VARCHAR(255),
    child_rule_id   INT,
    river_style_id  INT,

    CONSTRAINT fk_rule_bins_rule_id FOREIGN KEY (rule_id) REFERENCES rules(rule_id),
    CONSTRAINT fk_rule_bins_indicator_id FOREIGN KEY (indicator_id) REFERENCES indicators(indicator_id),
    CONSTRAINT fk_rule_bins_child_rule_id FOREIGN KEY (child_rule_id) REFERENCES rule_bins(child_rule_id),
    CONSTRAINT fk_rule_bins_river_style_id FOREIGN KEY (river_style_id) REFERENCES river_styles(river_style_id)
);
CREATE INDEX fx_rule_bins_rule_id ON rule_bins(rule_id);
CREATE INDEX fx_rule_bins_indicator_id ON rule_bins(idockerclearndicator_id);
CREATE INDEX fx_rule_bins_child_rule_id ON rule_bins(child_rule_id);
CREATE INDEX fx_rule_bins_river_style_id ON rule_bins(river_style_id);


CREATE TABLE geomorphic_units (
    unit_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    description     TEXT
);

CREATE TABLE variants (
    variant_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    description     TEXT
);

CREATE TABLE river_style_geomorphic_units (
    river_style_id  INT NOT NULL,
    variant_id      INT NOT NULL,
    unit_id         INT NOT NULL,

    CONSTRAINT pk_river_style_geomorphic_units PRIMARY KEY (river_style_id, variant_id, unit_id)
);

CREATE TABLE indicators (
    indicator_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) UNIT NOT NULL,
);


GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA public TO rstyler_data_steward;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO brat_data_steward;

-- GRANT INSERT, UPDATE, DELETE ON hydro_params TO brat_data_steward;
-- GRANT INSERT, UPDATE, DELETE ON watershed_hydro_params TO brat_data_steward;
-- GRANT UPDATE (default_suitability, notes) ON public.vegetation_types TO brat_data_steward;
-- GRANT UPDATE (q2,qlow,max_drainage, notes, ecoregion_id, metadata) ON watersheds TO brat_data_steward;